apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.code-editor/path: "" # user path
    app.kubernetes.io/instance: "" # app name
    app.kubernetes.io/managed-by: Helm
  name: "" # unique for user
spec:
  replicas: 1
  selector:
    matchLabels:
      app.code-editor/path: "" # user path
      app.kubernetes.io/instance: "" # app name
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.code-editor/path: "" # user path
        app.kubernetes.io/instance: "" # app name
    spec:
      containers:
      - name: "" # app name
        args:
        - --disable-telemetry
        - --disable-getting-started-override
        - --disable-workspace-trust
        image: codercom/code-server:4.22.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources: {}
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/coder/.local/share/code-server/User
          name: vscode-settings
        - mountPath: /home/coder/.ssh
          name: ssh-root
        - mountPath: /git
          name: data
        - mountPath: /home/coder
          name: cfg
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: "" # config name
              key: "" # unique for user
      dnsPolicy: ClusterFirst
      initContainers: []
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccountName: "" # app name
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vscode-settings
        secret:
          defaultMode: 420
          secretName: "" # config name
          items:
          - key: "" # unique for user
            path: "settings.json"
      - name: ssh
        secret:
          defaultMode: 420
          secretName: secret-ssh-auth
      - emptyDir: {}
        name: ssh-root
      - emptyDir: {}
        name: cfg
      - emptyDir: {}
        name: data
