apiVersion: v1
kind: Service
metadata:
  name: "" # unique for user
  labels:
    app.kubernetes.io/name: "" # unique for user
    helm.sh/chart: "" # unique for user
    app.kubernetes.io/instance: "" # app name
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.code-editor/path: "" # user path