apiVersion: v1
kind: ConfigMap
metadata:
  name: code-editor-users
data:
  users: |
    users:
    {{- $.Values.users | toYaml | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-editor-routes
data:
  service: |
    {{- .Files.Get "routes/service.yaml" | nindent 4 }}
  traefik-route: |
    {{- .Files.Get "routes/traefik-route.yaml" | nindent 4 }}
  secret: |
    {{- .Files.Get "routes/secret.yaml" | nindent 4 }}
  deployment: |
    {{- .Files.Get "routes/deployment.yaml" | nindent 4 }}
{{- if $.Values.codeServer.vscodeSettings.enable }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-config
data:
  settings.json: |
    {{- .Files.Get "vscode-settings.json" | nindent 4 }}
{{- end }}
