apiVersion: v1
kind: ConfigMap
metadata:
  name: code-editor-users
data:
  users: | 
    users:
    {{- range .Values.users }}
    - name: {{ .name }}
      password: {{ .password | quote }}
      path: {{ .path }}
    {{- end }}
