apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: server
      containers:
      - env:
        - name: PORT
          value: {{ quote .Values.server.server.env.port }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: API_SECRET
          value: {{ quote .Values.server.server.env.api.secret }}
        - name: API_TOKEN_EXPIRATION
          value: {{ quote .Values.server.server.env.api.tokenExpiration }}
        image: {{ .Values.server.server.image.repository }}:{{ .Values.server.server.image.tag
          | default .Chart.AppVersion }}
        name: server
        imagePullPolicy: {{ .Values.server.server.image.pullPolicy }}
        resources: {}
        volumeMounts:
        - name: users
          mountPath: "/server/assets"
          readOnly: true
        - name: routes
          mountPath: "/server/routes"
          readOnly: true
      volumes:
        - name: users
          configMap:
            name: code-editor-users
            items:
            - key: users
              path: users
        - name: routes
          configMap:
            name: code-editor-routes
            items:
            - key: service
              path: service
            - key: traefik-route
              path: traefik-route
            - key: secret
              path: secret
            - key: deployment
              path: deployment
