apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
spec:
  stripPrefix:
    prefixes:
    - /code-editor/api
    {{- range .Values.routes }}
    - /code-editor/{{ .path }}
    {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headers-manage
spec:
  headers:
    customRequestHeaders:
      Host: 'localhost'
      Content-Type: 'application/x-www-form-urlencoded'
      Access-Control-Allow-Credentials: 'true'
      Postman-Token: ''
      X-Forwarded-For: ''
      X-Forwarded-Host: ''
      X-Forwarded-Port: ''
      X-Forwarded-Prefix: ''
      X-Forwarded-Proto: ''
      X-Forwarded-Server: ''
      X-Real-Ip: ''
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
      - "HEADER"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "https://localhost:8005"
      - "https://{{ $.Values.domain }}"
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: code-editor-ui
spec:
  entryPoints:
    - websecure
  routes:
  {{- range .Values.routes }}
    - match: Host(`{{ $.Values.domain }}`) && PathPrefix(`/code-editor/{{ .path }}/`)
      kind: Rule
      services:
        - name: code-editor-{{ .name }}
          port: 8080
      middlewares:
        - name: strip-prefix
  {{- end }}
  tls:
    secretName: minio-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: code-editor-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $.Values.domain }}`) && PathPrefix(`/code-editor/api/`)
      kind: Rule
      services:
        - name: server
          port: 8082
      middlewares:
        - name: headers-manage
        - name: strip-prefix
        - name: cors
