apiVersion: v1
kind: Secret
metadata:
  name: secret-ssh-auth
type: Opaque
data:
  id_ed25519: |-
    {{ .Files.Get "ssh.key" | b64enc }}
{{- if not .Values.dev }}
---
apiVersion: v1
data:
  tls.crt: |-
          {{ .Files.Get "tls.crt" | b64enc }}
  tls.key: |-
          {{ .Files.Get "tls.key" | b64enc }}
kind: Secret
metadata:
  name: minio-tls
  namespace: code-editor
type: kubernetes.io/tls
{{- end }}
