apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-editor.fullname" . }}
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/name: {{ include "code-editor.name" . }}
    helm.sh/chart: {{ include "code-editor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.codeServer.password }}
  password: "{{ .Values.codeServer.password | b64enc }}"
  {{ else }}
  password: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}
{{- if .Values.dev }}
{{- else }}
---
apiVersion: v1
data:
  tls.crt: |-
          {{ .Files.Get "tls.crt" | b64enc }}
  tls.key: |-
          {{ .Files.Get "tls.key" | b64enc }}
kind: Secret
metadata:
  name: minio-tls
  namespace: code-editor
type: kubernetes.io/tls
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-ssh-auth
type: Opaque
data:
  id_ed25519: |-
    {{ .Files.Get "ssh.key" | b64enc }}
