apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-editor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "code-editor.name" . }}
    helm.sh/chart: {{ include "code-editor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.codeServer.service.type }}
  ports:
    - port: {{ .Values.codeServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- range .Values.codeServer.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "code-editor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: {{ .Values.server.type }}
  selector:
    app: server
  ports:
	{{- .Values.server.ports | toYaml | nindent 2 }}