apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-vscode.fullname" . }}
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/name: {{ include "open-vscode.name" . }}
    helm.sh/chart: {{ include "open-vscode.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.password }}
  password: "{{ .Values.password | b64enc }}"
  {{ else }}
  password: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}
