apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-server
rules:
- apiGroups: ["", "apps"]
  resources: ["pods","pods/exec","services","namespaces","deployments","deployments/scale","jobs","secrets"]
  verbs: ["list", "get", "update", "create", "delete", "watch"]
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutes"]
  verbs: ["list", "get", "update", "create", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-server
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-server
  namespace: '{{ .Release.Namespace }}'
