apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-templates
data:
  service: |
    {{- .Files.Get "assets/service.yaml" | nindent 4 }}
  traefik-route: |
    {{- .Files.Get "assets/traefik-route.yaml" | nindent 4 }}
  secret: |
    {{- .Files.Get "assets/secret.yaml" | nindent 4 }}
  deployment: |
    {{- .Files.Get "assets/deployment.yaml" | nindent 4 }}
  containers: |
    {{- .Files.Get "assets/containers.json" | nindent 4 }}
  vscode-config: |
    {{- .Files.Get "assets/vscode-settings.json" | nindent 4 }}
