apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      serviceAccountName: {{ .Release.Name }}-server
      containers:
      - env:
        - name: PORT
          value: {{ quote .Values.server.server.env.port }}
        - name: APP_NAME
          value: {{ .Release.Name }}
        - name: APP_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: API_SECRET
          value: {{ quote .Values.server.server.env.api.secret }}
        - name: API_TOKEN_EXPIRATION
          value: {{ quote .Values.server.server.env.api.tokenExpiration }}
        - name: AUTH_TYPE
          value: {{ .Values.authentication.type }}
        {{- if eq .Values.authentication.type "external" }}
        - name: AUTH_URL
          value: {{ .Values.authentication.url }}
        - name: AUTH_TOKEN_TYPE
          value: {{ .Values.authentication.token.type }}
        - name: AUTH_TOKEN_KEY
          value: {{ .Values.authentication.token.key }}
        - name: AUTH_QUERY
          value: {{ .Values.authentication.query }}
        {{- end }}
        image: {{ .Values.server.server.image.repository }}:{{ .Values.server.server.image.tag
          | default .Chart.AppVersion }}
        name: {{ .Release.Name }}-server
        imagePullPolicy: {{ .Values.server.server.image.pullPolicy }}
        resources: {}
        volumeMounts:
        - name: templates
          mountPath: "/server/assets/templates"
          readOnly: true
      volumes:
        - name: templates
          configMap:
            name: {{ .Release.Name }}-templates
            items:
            - key: service
              path: service.yaml
            - key: traefik-route
              path: traefik-route.yaml
            - key: secret
              path: secret.yaml
            - key: deployment
              path: deployment.yaml
            - key: containers
              path: containers.json
            - key: vscode-settings
              path: vscode-settings.json
{{- if .Values.console.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-console
  labels:
    app: {{ .Release.Name }}-console
spec:
  replicas: {{ .Values.console.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-console
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-console
    spec:
      serviceAccountName: {{ .Release.Name }}-console
      containers:
      - image: {{ .Values.console.image.repository }}:{{ .Values.console.image.tag
          | default .Chart.AppVersion }}
        name: {{ .Release.Name }}-console
        imagePullPolicy: {{ .Values.console.image.pullPolicy }}
        resources: {}
        ports:
        - containerPort: 80
        env:
        - name: BASE_HREF
          value: {{ quote .Values.console.env.baseHref }}
{{- end }}
