apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
spec:
  stripPrefixRegex:
    regex:
      - "/code-editor/[a-zA-Z]+/"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headers-manage
spec:
  headers:
    customRequestHeaders:
      Host: 'localhost'
      Content-Type: 'application/x-www-form-urlencoded'
      Access-Control-Allow-Credentials: 'true'
      Postman-Token: ''
      X-Forwarded-For: ''
      X-Forwarded-Host: ''
      X-Forwarded-Port: ''
      X-Forwarded-Prefix: ''
      X-Forwarded-Proto: ''
      X-Forwarded-Server: ''
      X-Real-Ip: ''
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
      - "DELETE"
      - "HEADER"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      {{- if .Values.console.enabled }}
      - {{ .Values.console.dev.url }}
      {{- end }}
      {{- if .Values.dev }}
      - "http://{{ $.Values.domain }}"
      {{- else }}
      - "https://{{ $.Values.domain }}"
      {{- end }}
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ui
spec:
  entryPoints:
    {{- if .Values.dev }}
    - web
    {{- else }}
    - websecure
    {{- end }}
  routes: []
  {{- if not .Values.dev }}
  tls:
    secretName: minio-tls
  {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-server
spec:
  entryPoints:
    {{- if .Values.dev }}
    - web
    {{- else }}
    - websecure
    {{- end }}
  routes:
    - match: Host(`{{ $.Values.domain }}`) && PathPrefix(`/code-editor/api/`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-server
          port: 8082
      middlewares:
        - name: headers-manage
        - name: strip-prefix
        - name: cors
