apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-users
type: Opaque
{{- if ne .Values.authentication.type "external" }}
stringData:
  users: |
    {{- range $index, $elem := .Values.users }}
    - id: local-{{ substr 1 5 (toString (add 10000 $index)) }}
      name: {{ $elem.name }}
      password: {{ $elem.password | quote }}
      {{- if $elem.isAdmin }}
      isAdmin: {{ $elem.isAdmin }}
      {{- end -}}
    {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
type: Opaque
{{- if not .Values.dev }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-tls
type: kubernetes.io/tls
data:
  tls.crt: |-
          {{ .Files.Get "assets/tls.crt" | b64enc }}
  tls.key: |-
          {{ .Files.Get "assets/tls.key" | b64enc }}
{{- end }}
