apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-users
type: Opaque
stringData:
  users.yaml: |
    users:
    {{- .Values.users | toYaml | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-ssh-auth
type: Opaque
data:
  id_ed25519: |-
    {{ .Files.Get "assets/ssh.key" | b64enc }}
{{- if not .Values.dev }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-tls
type: kubernetes.io/tls
data:
  tls.crt: |-
          {{ .Files.Get "assets/tls.crt" | b64enc }}
  tls.key: |-
          {{ .Files.Get "assets/tls.key" | b64enc }}
{{- end }}
