apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
spec:
  type: {{ .Values.server.type }}
  selector:
    app: {{ .Release.Name }}-server
  ports:
	{{- .Values.server.ports | toYaml | nindent 2 }}
