apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-console
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "code-editor.name" . }}
    helm.sh/chart: {{ include "code-editor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}
