apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
spec:
  type: {{ .Values.server.type }}
  selector:
    app: {{ .Release.Name }}-server
  ports:
	{{- .Values.server.ports | toYaml | nindent 2 }}
{{- if .Values.console.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-console
  labels:
    app: {{ .Release.Name }}-console
spec:
  type: {{ .Values.console.type }}
  selector:
    app: {{ .Release.Name }}-console
  ports:
	{{- .Values.console.ports | toYaml | nindent 2 }}
{{- end }}