openapi: 3.0.0

info:
  title: Code Editor API
  version: '1.0.0'
  description: |
    The Code Editor API allows you to manage users and code-server instances.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: http://localhost/code-editor/api/v1
    description: ''

paths:
  /ping:
    get:
      tags:
        - ping
      summary: Return paolo
      operationId: ping
      responses:
        '200':
          $ref: '#/components/schemas/MessageResponse'
  /login:
    post:
      tags:
        - login
      summary: Return the code-editor authentication token.
      operationId: login
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestBody'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /users:
    get:
      tags:
        - user
      summary: Return the list of Users
      operationId: user-list
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '403':
          description: User unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /users/register:
    post:
      tags:
        - user
      summary: Register new user
      operationId: user-register
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterRequestBody'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegisterResponse'
        '400':
          description: Missing configs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: External user not verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Already Registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: External authentication is not enabled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /users/unregister:
    post:
      tags:
        - user
      summary: Unregister user
      operationId: user-unregister
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUnregisterRequestBody'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserUnregisterResponse'
        '400':
          description: Missing configs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: External user not verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: A View instance is enabled for user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: External authentication is not enabled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /views:
    get:
      tags:
        - view
      summary: Return the list of View instances
      operationId: view-list
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewResponse'
    post:
      tags:
        - view
      summary: Create a new code-server instance.
      operationId: view-create
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewCreateRequestBody'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewCreateResponse'
        '400':
          description: Missing configs / Missing username param
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: code-server login error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: View instance already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Cannot create View instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - view
      summary: Update code-server instance with user's configurations
      operationId: view-config
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewConfigRequestBody'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewConfigResponse'
        '400':
          description: Missing configs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: User unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: View instance not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: code-server pod configuration failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - view
      summary: Destroy a code-server instance.
      operationId: view-destroy
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '403':
          description: User unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: View instance not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /views/:id:
    get:
      tags:
        - view
      summary: Return the View instance
      operationId: view-get
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewResponse'
        '404':
          description: View not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    MessageResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
    LoginResponse:
      allOf:
        - $ref: '#/components/schemas/MessageResponse'
        - type: object
          required:
            - data
          properties:
            data:
              type: object
              required: 
                - token
              properties: 
                token:
                  type: string
    UserRegisterResponse:
      allOf:
        - $ref: '#/components/schemas/MessageResponse'
        - type: object
          required:
            - data
          properties:
            data:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
    UserUnregisterResponse:
      properties:
        schemas:
          $ref: '#/components/schemas/MessageResponse'
    UserResponse:
      allOf:
        - $ref: '#/components/schemas/MessageResponse'
        - type: object
          required:
            - data
          properties:
            data:
              type: array
              items:
                required:
                  - id
                  - name
                properties:
                  id:
                    type: string
                  name:
                    type: string
    ViewResponse:
      allOf:
        - $ref: '#/components/schemas/MessageResponse'
        - type: object
          required:
            - data
          properties:
            data:
              type: array
              items:
                required:
                  - id
                  - name
                  - userId
                  - status
                  - path
                  - query
                  - password
                  - vscode-settings
                  - gitAuth
                  - session
                  - repoType
                  - repo
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  userId:
                    type: string
                  status:
                    type: string
                  path:
                    type: string
                  query:
                    type: string
                  password:
                    type: string
                  vscode-settings:
                    type: object
                  gitAuth:
                    type: boolean
                  session:
                    type: string
                  repoType:
                    type: string
                  repo:
                    type: string
    ViewCreateResponse:
      allOf:
        - $ref: '#/components/schemas/MessageResponse'
        - type: object
          required:
            - data
          properties:
            data:
              type: object
              required:
                - code-server-session
                - path
                - viewId
                - query-param
              properties:
                code-server-session:
                  type: string
                path:
                  type: string
                viewId:
                  type: string
                query-param:
                  type: string
    ViewConfigResponse:
      allOf:
        - $ref: '#/components/schemas/MessageResponse'
        - type: object
          required:
            - data
          properties:
            data:
              type: object
              required:
                - query-param
              properties:
                query-param:
                  type: string
    LoginRequestBody:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    UserRegisterRequestBody:
      type: object
      required:
        - token
        - password
      properties:
        token:
          type: string
          description: The external application's token
        password:
          type: string
          description: The password for the new registered user
    UserUnregisterRequestBody:
      type: object
      required:
        - token
        - username
        - force
      properties:
        token:
          type: string
          description: The external application's token
        username:
          type: string
          description: ''
        force:
          type: string
          description: if true, destroy a code-server instance before unregister
    ViewCreateRequestBody:
      type: object
      required:
        - git
      properties:
        name:
          type: string
          description: View name
        git:
          type: object
          description: Git configurations
          properties:
            name:
              type: string
            email:
              type: string
        extensions:
          type: string
          description: vs-code extensions configurations
          properties:
            id:
              type: string
            settings:
              type: object
        vscode-settings:
          type: object
          description: vs-code settings
        sshKey:
          type: string
          description: SSH key for git authentication
        gitSource:
          type: object
          description: Git Repository configurations
          properties:
            type:
              type: string
            org:
              type: string
            repo:
              type: string
            branch:
              type: string
            commit:
              type: string
    ViewConfigRequestBody:
      type: object
      required:
        - git
      properties:
        git:
          type: object
          description: Git repository to download
          properties:
            type:
              type: string
            org:
              type: string
            repo:
              type: string
            branch:
              type: string
            commit:
              type: string