name: Publish console

on:
  push:
    branches:
    - main
    - develop

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-docker-image:
    uses: ./.github/workflows/docker-push.yaml
    with:
      image-name: console
    permissions:
      contents: read
      packages: write
